VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

NKRO_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no
KEY_OVERRIDE_ENABLE = no